<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sysml</string>
	</array>
	<key>name</key>
	<string>SysML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment</string>
			<key>match</key>
			<string>--[^\n]*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.sysml</string>
			<key>match</key>
			<string>\b(bdd|act|ibd|pkg|par|req|seq|stm|uc|package|block|references|constraints|operations|post|values|pre|in|ports|owned|behaviors|initial|state|machine|choose|context|namespace|attributes|properties)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.sysml</string>
			<key>match</key>
			<string>\b(receive|after)\b</string>
		</dict>
		<dict>
		  <key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>string.sysml</string>
			<key>patterns</key>
			<dict>
				<key>include</key>
				<string>source.ocl</string>
			</dict>
		</dict>
		<!--dict>
			<key>name</key>
			<string>identifier</string>
			<key>match</key>
			<string>\b(receive|after)\b</string>
		</dict-->
		<dict>
			<key>name</key>
			<string>entity.name.type.sysml</string>
			<key>match</key>
			<string>\b[A-Z][A-Za-z0-9_]*\b</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sysml</string>
	<key>uuid</key>
	<string>11345C32-717C-11F9-A948-010D93589AF6</string>
</dict>
</plist>
